name: ✨ Solicitar Nova Funcionalidade
description: Use este formulário para sugerir melhorias ou novas funcionalidades para o sistema
title: "[FUNCIONALIDADE] "
labels: ["enhancement", "feature-request"]
assignees: ["copilot"]
body:
  - type: markdown
    attributes:
      value: |
        Use este formulário para sugerir melhorias ou novas funcionalidades que facilitariam seu trabalho no sistema.
        
        **Dica**: Pense em como esta funcionalidade ajudaria você e outros professores no dia a dia.

  - type: input
    id: feature-summary
    attributes:
      label: Resumo da Funcionalidade
      description: Em uma frase, qual funcionalidade você gostaria de ter?
      placeholder: Ex. "Exportar lista de participantes para Excel", "Enviar emails automáticos para pais"
    validations:
      required: true

  - type: textarea
    id: problem-description
    attributes:
      label: Qual problema isso resolveria?
      description: Descreva a dificuldade ou limitação atual que esta funcionalidade ajudaria a resolver
      placeholder: |
        Ex. "Atualmente preciso copiar manualmente os nomes dos alunos do sistema para criar as listas de presença. Isso demora muito tempo e às vezes cometo erros."
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Como você imagina que funcionaria?
      description: Descreva como você gostaria que esta funcionalidade funcionasse
      placeholder: |
        Ex. "Gostaria de ter um botão 'Exportar Lista' na página de cada atividade que baixasse um arquivo Excel com os nomes, emails e telefones dos alunos inscritos."
    validations:
      required: true

  - type: dropdown
    id: user-type
    attributes:
      label: Quem se beneficiaria desta funcionalidade?
      description: Quem usaria esta nova funcionalidade?
      options:
        - Apenas eu
        - Professores coordenadores de atividades
        - Todos os professores
        - Professores e secretaria
        - Professores e direção
        - Toda a equipe escolar
        - Alunos também
        - Pais também
    validations:
      required: true

  - type: dropdown
    id: frequency
    attributes:
      label: Com que frequência usaria esta funcionalidade?
      options:
        - Diariamente
        - Algumas vezes por semana
        - Semanalmente
        - Mensalmente
        - Algumas vezes por semestre
        - Raramente, mas seria muito útil quando precisasse
    validations:
      required: true

  - type: textarea
    id: current-workaround
    attributes:
      label: Como você resolve isso atualmente?
      description: O que você faz hoje para resolver este problema? Quanto tempo demora?
      placeholder: |
        Ex. "Hoje eu abro o sistema, copio os nomes um por um para um documento Word, depois formato e imprimo. Isso me toma cerca de 30 minutos para cada atividade."

  - type: dropdown
    id: impact
    attributes:
      label: Qual seria o impacto desta funcionalidade?
      options:
        - Crítico - Resolveria um problema muito sério
        - Alto - Facilitaria muito meu trabalho diário
        - Médio - Seria uma melhoria útil
        - Baixo - Seria uma conveniência adicional
    validations:
      required: true

  - type: textarea
    id: examples
    attributes:
      label: Exemplos ou casos de uso específicos
      description: Forneça exemplos específicos de quando e como usaria esta funcionalidade
      placeholder: |
        Ex. "No início do semestre quando preciso criar as listas de presença para todas as 12 atividades extracurriculares. Também antes dos eventos quando preciso enviar informações específicas para os pais dos alunos participantes."

  - type: textarea
    id: alternatives
    attributes:
      label: Outras soluções que considerou
      description: Pensou em alguma alternativa? Por que esta seria a melhor opção?
      placeholder: |
        Ex. "Pensei em usar uma planilha externa, mas seria melhor ter tudo integrado no mesmo sistema para evitar erros de sincronização."

  - type: dropdown
    id: priority
    attributes:
      label: Prioridade
      description: Quão importante é esta funcionalidade para você?
      options:
        - Alta - Preciso urgentemente
        - Média - Seria muito útil ter em breve
        - Baixa - Seria bom ter, mas não é urgente
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Informações adicionais
      description: Qualquer outra informação que possa ajudar no desenvolvimento desta funcionalidade
      placeholder: |
        Ex. "Esta funcionalidade seria especialmente útil no período de matrículas quando há mais movimento de alunos entrando e saindo das atividades."