name: "Copilot Setup Steps"

on: workflow_dispatch
jobs:
  # Este é o nome de job obrigatório. Se for diferente, o Copilot irá ignorar.
  copilot-setup-steps:
    runs-on: ubuntu-latest

    # Concede acesso antecipado ao Copilot para ler o conteúdo do repositório.
    permissions:
      contents: read

    steps:
      - name: Fazer checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
          cache: "pip"

      - name: Instalar dependências Python
        run: |
          python -m pip install --upgrade pip
          pip install -r src/requirements.txt
